Require pytest>=6.1.0
With older versions, Mypy fails with:

    src/darker/tests/helpers.py:29: error: Returning Any from function declared to return "Union[RaisesContext[Any], ContextManager[None]]"
    Found 1 error in 1 file (checked 32 source files)